---
include:
  # Cornix
  - board: cornix_left
    artifact-name: cornix_left_default

  - board: cornix_ph_left
    artifact-name: cornix_left_for_dongle

  - board: cornix_right
    artifact-name: cornix_right

  # Totem
  - board: seeeduino_xiao
    shield: totem_left
    artifact-name: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DBOARD_ROOT="/zmk-config/zmk-config-totem/config"

  - board: seeeduino_xiao
    shield: totem_right
    artifact-name: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DBOARD_ROOT="/zmk-config/zmk-config-totem/config"

  - board: seeeduino_xiao
    shield: totem_left
    artifact-name: totem_left_for_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DBOARD_ROOT="/zmk-config/zmk-config-totem/config"

  # Reset shields
  - board: cornix_right
    shield: settings_reset
    artifact-name: cornix_reset

  - board: seeeduino_xiao
    shield: settings_reset
    artifact-name: totem_reset
