---
include:
  # Cornix
  - board: cornix_left
    artifact-name: cornix_left_default

  - board: cornix_ph_left
    artifact-name: cornix_left_for_dongle

  - board: cornix_right
    artifact-name: cornix_right

  - board: cornix_dongle
    shield: cornix_dongle_eyelash dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: cornix_dongle

  # Forager
  - board: seeeduino_xiao_ble
    shield: forager_left
    artifact-name: forager_left

  - board: seeeduino_xiao_ble
    shield: forager_right
    artifact-name: forager_right

  - board: seeeduino_xiao_ble
    shield: forager_left
    artifact-name: forager_left_for_dongle

  # Reset shields
  - board: cornix_right
    shield: settings_reset
    artifact-name: cornix_reset

  - board: seeeduino_xiao
    shield: settings_reset
    artifact-name: totem_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: forager_reset

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: dongle_reset
